### ISSUE TITLE
Suitable for production?

### ISSUE THREAD

**Issue by cyberjoac** [arctelix/django-invitation#2]
Hello,

Your package looks really good.
Have you tried it with Django 1.6?

Is it suitable for production?

Thanks a lot.

**Comment by arctelix** [comment]
I have used it in a production alpha test on django 1.6 / python 2.7 with light traffic and i experianced no issues.  I do intend to use this package for production on a current project in development. Let me know if you have any issues and i'm happy to resolve them.
