### ISSUE TITLE
Possibility to send link that doesn't need invitation request

### ISSUE THREAD

**Issue by cyberjoac** [arctelix/django-invitation#3]
Hi,

Thanks for your fast answer.
So far I am using django-hunger and was wondering if there is a possibility for a similar workflow.
In django-hunger, there are a few possibilities:
- User registers with regular registration, and then admin can send invitation from django admin
- Admin sends to user a "special link" that includes a registration code, gets inserted in the session cookie, and bypasses the need to be activated by admin (automatic activation).

Which of those workflows does django-invitation support out of the box?
Is it complicated to implement a similar workflow?

For reference: https://github.com/joshuakarjala/django-hunger

Thanks a lot for your help!!

**Comment by arctelix** [comment]
Right now django-invitation is set up for admins and registered users to send invitations.  Invitation recipiants are then able to signup with that invitation link.

To answer your question, i believe what you want can be easily implimented in the adapter without having to modify base code.  

Just allow all registrations and assign users without an invitation a user_group with inactive status. You can then use admin to view inactive users and send invites at your discression.

Let me know if this solution does not work out.

**Comment by arctelix** [comment]
Actually let me clarify:

The suggestion above is for the first use case you requested.

The second is supported out of the box pluse many other features which integrate seamlessly with allauth or django's auth backend.  It also supports adnims granting auth users a quantity of invites to send if desired.
