### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by abendig** [arctelix/django-invitation#4]
The following links don't work right: 
* https://github.com/lizrice/django-invitation (404)
* http://code.larlet.fr/django-invitation (bitbucket homepage)

That second link is unfortunately referenced in the documentation as containing setup instructions.

**Comment by arctelix** [comment]
https://bitbucket.org/david/django-invitation

Here is a link to what appear to be the original source. However, the docs directory in this repository contain detailed setup instructions.
